resources:
  folds:
    root: /home/prj_vcfgeno/data/malva_gw_small
    tools : /home/prj_vcfgeno/software/
    in : input
    mid : mid
    out: output
  files:
    ref : hs37d5.fa
    vcf : 1kgen.ph3.EUR.vcf
    vcf_for_vargeno : 1kgen.ph3.EUR.vargeno.vcf
    sample_name : RMNISTHS_30xdownsample
  info:
    truth_sample : NA12878
    pop : EUR
    k : 35
    K : 57
