resources:
  folds:
    root: /data/malva_exps
    tools : /home/prj_vcfgeno/software
    refs : refs
    vcfs : vcfs
    samples : samples
    res : results
  malva : malva
  kmc : KMC
  vargeno : vargeno
  big_bam : RMNISTHS_30xdownsample.bam
  truth_sample : NA12878
  chroms:
    - chr1
    - chr8
    - chr17
    - chr14
    - chr22
  samples:
    - original
    # - corrected
  vcf_types:
    # - full
    - EUR
